apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: stresstest-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: stress
    spec:
      containers:
      - name: stress
        image: tkubica/stress
        env:
        - name: STRESS_TIMEOUT
          value: "240"
        resources:
          limits:
            cpu: 0.2
      nodeSelector:
        beta.kubernetes.io/os: linux